/*global module:false*/
module.exports = function(grunt) {
    require('time-grunt')(grunt);
    var pkg = grunt.file.readJSON('package.json');

    // Project configuration.
    grunt.initConfig({
        pkg: pkg,

        banner: '/*! <%= pkg.title || pkg.name %> - v<%= pkg.version %> - ' +
        '<%= grunt.template.today("yyyy-mm-dd") %>\n' +
        '<%= pkg.homepage ? "* " + pkg.homepage + "\\n" : "" %>' +
        '* Copyright (c) <%= grunt.template.today("yyyy") %> <%= pkg.author %>;' +
        ' Licensed <%= _.pluck(pkg.licenses, "type").join(", ") %> */\n',

        compass: {
            options: {
                basePath: 'public/'
            },
            dist: {
                options: {
                    environment: 'production',
                    outputStyle: 'compressed',
                    force: true
                }
            },
            dev: {
                options: {
                    environment: 'development',
                    outputStyle: 'expanded'
                }
            }
        },

        concat: {
            options: {
                stripBanners: true
            },
            dist: {
                src: [
                    "public/js/core.js",
                    "public/js/leaflet-providers.js",
                    "public/js/config.js",
                    "public/js/my_position.js",
                    "public/js/markers.js",
                    "public/js/refresh.js",
                    "public/js/fuzzy.js",
                    "public/js/search.js",
                    "public/js/main.js"
                ],
                dest: 'public/js/build/' + pkg.name + '.js'
            }
        },

        jshint: {

            all: [
                'Gruntfile.js', 
                'public/js/**/*.js',
            ],
            options: {
                ignores: [
                    'public/**/*.min.js',
                    'public/js/build/*.js',
                    'public/js/leaflet-providers.js'
                ],
                jshintrc: true
            },
            gruntfile: {
                src: 'Gruntfile.js'
            }
        },

        uglify: {
            dist: {
                src: '<%= concat.dist.dest %>',
                dest: 'public/js/build/' + pkg.name + '.min.js'
            }
        },

        processhtml: {
            options: {
                data: {
                    version: pkg.version,
                    buildNotice: '<!--\n\tIMPORTANT! This file is generated by grunt:build.\n\tDo not edit this file. All changes will be\n\toverwritten by the next build.\n\tYou should edit index-dev.html instead.\n-->'
                }
            },
            dist: {
                files: {
                    'public/index.html': ['public/index-dev.html']
                }
            }
        }

    });

    // autoload tasks
    require('load-grunt-tasks')(grunt);

    grunt.registerTask('build', ['jshint', 'concat:dist', 'uglify:dist', 'compass:dist', 'processhtml:dist']);
};
